PROJECT_LOCAL_PATH: /Users/haohuanw/Documents/forfun/caencompiler/
PROJECT_REMOTE_PATH: /Users/haohuanw/caen/
GITHUB_ADDR: https://github.com/haohuanw/caencompiler.git
HOST: localhost 
USER: haohuanw
PASSWORDS: 890922hH!@#
